# EA SPORTS FC 2025 eSports Platform - Filebeat Configuration
filebeat.inputs:
  # Application logs
  - type: log
    enabled: true
    paths:
      - /var/log/nginx/*.log
      - /app/logs/*.log
    fields:
      service: esports-platform
      environment: production
    fields_under_root: true
    multiline.pattern: '^\d{4}-\d{2}-\d{2}'
    multiline.negate: true
    multiline.match: after

  # Docker container logs
  - type: container
    enabled: true
    paths:
      - '/var/lib/docker/containers/*/*.log'
    processors:
      - add_docker_metadata:
          host: "unix:///var/run/docker.sock"
      - decode_json_fields:
          fields: ["message"]
          target: ""
          overwrite_keys: true

  # System logs
  - type: log
    enabled: true
    paths:
      - /var/log/syslog
      - /var/log/auth.log
    fields:
      service: system
      environment: production
    fields_under_root: true

# Processors
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~

# Output to Elasticsearch
output.elasticsearch:
  hosts: ["${ELASTICSEARCH_HOSTS:elasticsearch:9200}"]
  index: "esports-platform-logs-%{+yyyy.MM.dd}"
  template.name: "esports-platform"
  template.pattern: "esports-platform-*"
  template.settings:
    index.number_of_shards: 1
    index.number_of_replicas: 0
    index.refresh_interval: 5s

# Logging configuration
logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644

# Monitoring
monitoring.enabled: true
monitoring.elasticsearch:
  hosts: ["${ELASTICSEARCH_HOSTS:elasticsearch:9200}"]

# Setup template and index lifecycle management
setup.template.enabled: true
setup.template.name: "esports-platform"
setup.template.pattern: "esports-platform-*"
setup.ilm.enabled: true
setup.ilm.rollover_alias: "esports-platform"
setup.ilm.pattern: "{now/d}-000001"