# EA SPORTS FC 2025 eSports Platform - Prometheus Configuration
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'esports-platform-monitor'

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Backend API instances
  - job_name: 'backend'
    static_configs:
      - targets: 
        - 'backend:3001'
        - 'backend-1:3001'
        - 'backend-2:3001'
        - 'backend-3:3001'
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Frontend (nginx metrics)
  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:80']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # PostgreSQL database
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Redis cache
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # NGINX load balancer
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: '/nginx_status'
    scrape_interval: 15s

  # Node Exporter (system metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # Docker containers
  - job_name: 'docker'
    static_configs:
      - targets: ['docker-exporter:9417']
    scrape_interval: 30s

  # Application-specific metrics
  - job_name: 'esports-tournaments'
    static_configs:
      - targets: ['backend:3001']
    metrics_path: '/api/metrics/tournaments'
    scrape_interval: 60s

  - job_name: 'esports-matches'
    static_configs:
      - targets: ['backend:3001']
    metrics_path: '/api/metrics/matches'
    scrape_interval: 30s

  - job_name: 'esports-users'
    static_configs:
      - targets: ['backend:3001']
    metrics_path: '/api/metrics/users'
    scrape_interval: 60s

  # Real-time streaming metrics
  - job_name: 'streaming'
    static_configs:
      - targets: ['backend:3001']
    metrics_path: '/api/metrics/streaming'
    scrape_interval: 15s

  # AI service metrics
  - job_name: 'ai-services'
    static_configs:
      - targets: ['backend:3001']
    metrics_path: '/api/metrics/ai'
    scrape_interval: 30s